server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database01
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      show-sql: true
